### PR TITLE
Feature/week9 homework

### PR DESCRIPTION
**Pull request by Bartozo**
My project for week 9.
I added 2 tests. One is for viewmodel and another if for class model.

My viewModel is using repository which is connected with the database, so i need to use android context. I remember that someone mentioned to use Test instead of AndroidTest. I couldn't "finish" it without getting access to android context which is required for room database. 

Anyway, I tried my best in previous week to use MVVM pattern as much as possible, so there is only test commits in this week.

### CODE REVIEW

**Comment by abunur** [comment]
I would delete the example Unit Test and other sample tests in the application. Those are place holders to help you get started, but it's nice to clean up and get rid of them now that you don't need them.

**Comment by Bartozo** [comment]
I removed the example tests from the project.

**Comment by abunur** [comment]
you had a lot of warnings in various files in the app. You should take the time to clean up all the warnings before making your PR. It will leave a better impression with your reviewer.

The homework was supposed to build on the previous week's homework. Your app is OK, but it only has one screen. If you had built on the prior homework there would have been more screens and more complexity, and you would have benefitted from getting more practice implementing the tests, view models and dealing with separation of concerns. Your grade for this assignment is "good job"

**Comment by Bartozo** [comment]
I think I have fixed these issues in the next PRs, but I will check one more time to make sure. (I mean the warnings). 

I would like to add more stuff (more screens), but API in my project is very simple.

**Pull request merged**
